[project]
name = "voice2note"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhangtony239", email = "zhangtony239@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
voice2note = "voice2note:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
