[project]
name = "voice2note"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhangtony239", email = "zhangtony239@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "av>=16.0.0",
    "librosa>=1.0.0",
    "openai>=2.9.0",
    "pyyaml>=6.0.3",
    "ruff>=0.16.8",
    "torch>=2.14.0",
    "torchaudio>=2.11.0",
    "tqdm>=4.66.5",
    "transformers>=5.17.0",
]

[project.scripts]
v2n = "voice2note.cli:main"

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/xpu"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
